server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${moye.datasource.driver-class-name}
    url: jdbc:mysql://${moye.datasource.host}:${moye.datasource.port}/${moye.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${moye.datasource.username}
    password: ${moye.datasource.password}
  data:
    redis:
      host: ${moye.redis.host}
      port: ${moye.redis.port}
      database: ${moye.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.moye.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      moye:
        mapper: debug
        service: info
        controller: info

moye:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: moye
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token


# http://localhost:8080/doc.html#/home
# http://localhost:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'Admin'
      display-name: '管理员接口'
      paths-to-match: '/admin/**'
      packages-to-scan: com.moye.controller.admin
    - group: 'User'
      display-name: '用户接口'
      paths-to-match: '/user/**'
      packages-to-scan: com.moye.controller.user
  default-flat-param-object: true


knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  basic:
    enable: false
    username: abc
    password: 123
